---
ingress:
  - hostname: "pghd.vl3box.com"
    service: tcp://postgres-pgbouncer.database.svc:5432
  - hostname: "vl3box.com"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: e.vl3box.com
      noTLSVerify: true
  - hostname: "*.vl3box.com"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: e.vl3box.com
      noTLSVerify: true
  - hostname: "*.prev.vl3box.com"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: e.prev.vl3box.com
      noTLSVerify: true
  - service: http_status:404
