---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitwarden-eso
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: bitwarden-eso-provider
      version: 0.9.1
      sourceRef:
        kind: HelmRepository
        name: small-hack
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    bitwarden_eso_provider:
      create_cluster_secret_store: true
      auth:
        existingSecret: "bitwarden-eso"
