apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLUSTER_SECRET_CPGO_R2_ENDPOINT: ENC[AES256_GCM,data:r6TrPMvU/SxjZrXSd8TfomiMk3flTHrYkXovvDCWMQ4PJDF7j8+0tYVGRP8Ol24MESVmF6pvoZIa,iv:LQwcOhPN1Zizy73mvKVQYyLkxfT7gLEMrHWc3vGl/j0=,tag:2oxbhOQJ3sVCg+seXfUkWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ktq3kavysyvghws0y3ex052l5vp2fjhvfplax9jj2tyfwmaae9lqqmlk3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRjNKZ0pWYXJSbzNLNjg5
            VEo0WmxMbVNRWWxsRXEwdmpIQ0VaSzRFNWg0CnU1eTg4L2lVVDVqTm92MHBBamw0
            QjluR0d0ZSt3d1BtSTJ5U0JRanVDUVUKLS0tIEE3OEZacmxyQ0hVOG1QbDBNQ3dB
            UEpxekdQejB4VVNZcE1CSWp3TVBaUlEKx092r76OC8OJcyqYIo2ZCUqhlLoJ/47k
            MEgX8bzoXO97xxUnduF3bhOnR+NLRbrfuMYiR3EfgEsIwPpCWpChxw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qfahhjuu2yqn039q40jk4zd3kulvd2ngey82cvx55zakf36pmvxsrtmq8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlL0hvL2dxNzV1QVFDK2dF
            OGh3QURCWGpJRHZyRURXU2t4SUVuWU1oSGxRCkQ1aE1zUzAxaSs2Y2hZdXFkdVRZ
            WmlJN3BKOWgwSmNoNE4wT2FlOVpPU0UKLS0tIHcvU1JlZFcrSi9SREdBT2NEb1pF
            SVI3NUJrM2oxYzlVb1ovSnNTNmxlVkkKKkWA4Zp6igUHt0pjMrkQYBrLFNs3ZpB6
            XMOLZWVsGlZgzfm/RBtp+XQnikqlK6bP1BWRiUKZ1PQR3pKCxEMkNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T07:58:10Z"
    mac: ENC[AES256_GCM,data:/UfGHYVkmVmhbiW2eAtmDQ2mLN/vUX/gEb17Gj2adSbhTd/KqJOrtktiU3BUCf879uGlq1fVNTdpAekqu6/gdzJ0gRf48vjzQIL4Fo4XJamyPptO3riks92amuygHKqA8LaZo/ZyVg+EXltId91uzsPbdQ5NCkmAXpb/hzn4rGk=,iv:C2CPUVvuQXIqu9MJmdIPz6Nsk39XkXfakO86XY+E62c=,tag:y6GrdWQgl35vd54/ZbIw1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
