---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname vl3box-backend
  namespace: flux-system
spec:
  targetNamespace: vl3box
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 12h
  retryInterval: 1m
  timeout: 5m
  path: "./kubernetes/vl3box/apps/vl3box/backend/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: vl3box-ops
  wait: true
