---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name crunchy-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: crunchy-postgres-secret
    template:
      engineVersion: v2
      data:
        s3.conf: |
          [global]
          repo1-s3-key={{ .minio_crunchy_postgres_access_key }}
          repo1-s3-key-secret={{ .minio_crunchy_postgres_secret_key }}
          repo2-s3-key={{ .cloudflare_cpgo_access_id }}
          repo2-s3-key-secret={{ .cloudflare_cpgo_access_key }}
        encryption.conf: |
          [global]
          repo1-cipher-pass={{ .crunchy_postgres_backup_encryption_cipher }}
          repo2-cipher-pass={{ .crunchy_postgres_backup_encryption_cipher }}
  dataFrom:
    - extract:
        key: vl3box-crunchy
      rewrite:
        - regexp:
            source: "(.*)"
            target: "crunchy_postgres_$1"
    - extract:
        key: minio
      rewrite:
        - regexp:
            source: "[-]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "minio_$1"
    - extract:
        key: vl3box-cloudflare
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9 -]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "cloudflare_$1"