---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: &name postgres
spec:
  postgresVersion: 16

  metadata:
    labels:
      crunchy-userinit.ramblurr.github.com/enabled: "true"
      crunchy-userinit.ramblurr.github.com/superuser: "postgres"

  service:
    type: LoadBalancer
    metadata:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: p.vl3box.com
        io.cilium/lb-ipam-ips: 10.10.20.34

  patroni: # turn on sync writes to at least 1 other replica
    dynamicConfiguration:
      synchronous_mode: false
      postgresql:
        synchronous_commit: "on"
        pg_hba:
          - hostnossl all all 10.244.0.0/16 md5 # Needed because dbman does not support SSL yet
          - hostssl all all all md5

  instances:
    - name: postgres
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres
      replicas: &replica 1
      dataVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     topologyKey: "kubernetes.io/hostname"
      #     whenUnsatisfiable: "DoNotSchedule"
      #     labelSelector:
      #       matchLabels:
      #         postgres-operator.crunchydata.com/cluster: *name
      #         postgres-operator.crunchydata.com/data: postgres

  users:
    # Superuser
    - name: postgres
      databases:
        - postgres
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
    # Applications
    - name: vl3box
      databases:
        - vl3box
      password:
        type: AlphaNumeric
    - name: vl3box-dev
      databases:
        - vl3box-dev
      password:
        type: AlphaNumeric
          
  backups:
    pgbackrest:
      configuration: &backupConfig
        - secret:
            name: crunchy-postgres-secret
      global: &backupFlag
        archive-timeout: "60"
        compress-type: "bz2"
        compress-level: "9"
        delta: "y"
        archive-push-queue-max: 4GiB

        repo1-storage-verify-tls: "n"
        repo1-retention-full-type: "time"
        repo1-retention-full: "1"
        repo1-retention-diff: "1"
        repo1-path: "/crunchy-pgo"
        repo1-s3-uri-style: path

        # R2
        repo2-block: "y"
        repo2-bundle: "y"
        repo2-path: /crunchy-pgo
        repo2-retention-full: "1" # days
        repo2-retention-full-type: time
        repo2-s3-uri-style: path
      manual:
        repoName: repo1
        options:
          - --type=full
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres-backup
      repos:
        - name: repo1 # Minio
          s3: &minio
            bucket: "vl3box-crunchydata"
            endpoint: "s3.vl3box.com:9000"
            region: "us-east-1"
          schedules:
            full: "0 1 * * 0" # Sunday at 01:00
            differential: "0 1 * * 1-6" # Mon-Sat at 01:00
            incremental: "0 2-23/3 * * *" # Every hour except 01:00
        - name: repo2 # R2
          s3: &r2
            bucket: "vl3box-crunchydata"
            endpoint: ${CLUSTER_SECRET_CPGO_R2_ENDPOINT}
            region: "us-east-1"
          schedules:
            full: "0 2 * * 0" # Sunday at 02:00
            incremental: "0 2 * * 1-6/2" # Mon-Sat at 02:00, every 2nd day

  # dataSource:
  #   pgbackrest:
  #     stanza: "db"
  #     configuration: *backupConfig
  #     global: *backupFlag
  #     repo:
  #       name: "repo1"
  #       s3: *minio

  proxy:
    pgBouncer:
      port: 5432
      replicas: *replica
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres-pgbouncer
      config:
        global:
          pool_mode: "transaction"
          client_tls_sslmode: prefer
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: *name
              postgres-operator.crunchydata.com/role: "pgbouncer"
