---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vl3box-pull
spec:
  interval: 12h
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      pull:
        annotations:
          secret.reloader.stakater.com/reload: vl3box-db-secret
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
        containers:
          app:
            image:
              repository: ghcr.io/wei/pull
              tag: latest
            envFrom:
              - secretRef:
                  name: vl3box-pull-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: pull
        ports:
          http:
            port: 3000

    ingress:
      app:
        className: "external-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: e.vl3box.com
        hosts:
          - host: &hostName pull.vl3box.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *hostName

    persistence:
      tmpfs:
        enabled: true
        type: emptyDir
        advancedMounts:
          pull:
            app:
              - path: /.npm
                subPath: .npm
