---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vl3box-backend
spec:
  interval: 12h
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      backend:
        annotations:
          secret.reloader.stakater.com/reload: vl3box-db-secret
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
        containers:
          app:
            image:
              repository: ghcr.io/vl3box/vl3box-backend
              tag: vl3box@sha256:7a589431e79ed87ddfaba5fdad4e2acd1c955873b49b57b540d8bb4df821f56f
            env:
              LOG_LEVEL: info
              NODE_ENV: production
              DATABASE_AUTH_TOKEN: nothing
              PORT: 3000
            envFrom:
              - secretRef:
                  name: vl3box-db-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: backend
        ports:
          http:
            port: 3000

    ingress:
      app:
        className: "external-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: e.vl3box.com
        hosts:
          - host: cms.vl3box.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: data.vl3box.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: helper.vl3box.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: next2.vl3box.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: node.vl3box.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: spider2.vl3box.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: pay.vl3box.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: team.vl3box.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: server.vl3box.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

        tls:
          - hosts:
              - cms.prev.vl3box.com
              - data.prev.vl3box.com
              - helper.prev.vl3box.com
              - next2.prev.vl3box.com
              - node.prev.vl3box.com
              - spider2.prev.vl3box.com
              - pay.prev.vl3box.com
              - team.prev.vl3box.com
              - server.prev.vl3box.com
