---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Meta - Enforce PR labels

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize
      - labeled
      - unlabeled

jobs:
  enforce-label:
    name: Enforce PR labels
    runs-on: ubuntu-22.04
    container: catthehacker/ubuntu:act-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          BANNED_LABELS: "do-not-merge"
