---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Meta - Labeler

on:
  pull_request:
    branches:
      - main

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-22.04
    container: catthehacker/ubuntu:act-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      # - name: Generate Token
      #   uses: actions/create-github-app-token@v1
      #   id: app-token
      #   with:
      #     app-id: ${{ secrets.BJWS_APP_ID }}
      #     private-key: ${{ secrets.BJWS_APP_PRIVATE_KEY }}

      - name: Labeler
        uses: actions/labeler@v5
        with:
          # repo-token: "${{ steps.app-token.outputs.token }}"
          repo-token: ${{ secrets.GH_LABELER_TOKEN }}
          configuration-path: .github/labeler.yaml
